name: CI Test

on: [push, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        dir: ["./frontend", "./backend"]

    name: ${{ matrix.dir }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ${{ matrix.dir }}
        run: yarn install

      - name: Test
        working-directory: ${{ matrix.dir }}
        run: yarn test

      - name: Typecheck
        working-directory: ${{ matrix.dir }}
        run: yarn typecheck

      - name: Lint
        working-directory: ${{ matrix.dir }}
        run: yarn lint

      - name: Prettiercheck
        working-directory: ${{ matrix.dir }}
        run: yarn prettiercheck

      - name: Build
        working-directory: ${{ matrix.dir }}
        run: yarn build
