# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install npm and yarn and run tests across stable and canary builds on Windows, Ubuntu and macOS.

name: Yarn [frontend]

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: frontend test
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup NodeJs 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Test
        working-directory: ./frontend
        run: yarn test

      - name: Typecheck
        working-directory: ./frontend
        run: yarn typecheck

      - name: Linter
        working-directory: ./frontend
        run: yarn lint
