name: CI Test

on:
  push
  pull_request:
    branches: [main]

jobs:
  test:
    name: frontend
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup NodeJs 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Test
        working-directory: ./frontend
        run: yarn test

      - name: Typecheck
        working-directory: ./frontend
        run: yarn typecheck

      - name: Linter
        working-directory: ./frontend
        run: yarn lint

  test:
    name: backend
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup NodeJs 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./backend
        run: yarn install

      - name: Test
        working-directory: ./backend
        run: yarn test

      - name: Typecheck
        working-directory: ./backend
        run: yarn typecheck

      - name: Linter
        working-directory: ./backend
        run: yarn lint
